import "./globals.css";

import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body className="bg-background text-foreground h-full">
        <main className="container mx-auto min-h-screen lg:h-screen flex flex-col py-6">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
