import "./globals.css";

import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="dark bg-background text-foreground">
        <main className="container pt-8">
          <h1 className="text-4xl font-bold text-center mb-8">DASHBOARD</h1>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
